### ISSUE TITLE
KeyError: 'outputs' when module has no outputs defined

### ISSUE THREAD

**Issue by ldealmei** [GoogleCloudPlatform/terraform-python-testing-helper#10]
I've been exploring the package to test my terraform modules and got confronted to this error and it was a bit confusing to debug.

When no `output` blocks are defined in the Terraform configuration, setting up tests like this (see below) raises a `KeyError: 'outputs'`. Adding a output block in the module fixes the problem.
```py
@pytest.fixture
def tfplan():
    tf_vars = {
        'my_var': 'value
    }
    TF.setup(
        extra_files=[
            os.path.join(ROOT, '../', 'vars.tf')])
    plan = TF.plan(tf_vars=tf_vars, output=True)
    return plan
```

However Terraform configurations without output blocks are valid so we should be able to test them in the same way.

Would it make sense for you to prevent this error when no output is configured? If yes, I'd love to contribute a PR.

Cheers

**Comment by ludoo** [comment]
Thanks for deep diving on this. It does make absolute sense to tolerate configurations with no outputs defined. If you have the time for a PR, it's of course more than welcome. Otherwise I'll try to get around to it next week.

**Comment by ludoo** [comment]
The fix might be trivial. Can you check that the code in the branch above works for you?

**Comment by ldealmei** [comment]
Works perfect! Thanks a lot for the reactivity :)

**Comment by ludoo** [comment]
Ahah thanks for confirming! Will merge and push on pypi shortly. Thanks a lot for the detailed report!
