### ISSUE TITLE
Adding extra vars file

### ISSUE THREAD

**Issue by tangel0v** [GoogleCloudPlatform/terraform-python-testing-helper#14]
Hi, I only have a question:

Is it possible to add extra variables to terraform in the terraform plan wrapper? I have been trying to use it and it only adds the variables if they use *.auto.tfvars.

I want to replicate this execution "terraform plan --var-file=my-secret.tfvars"

Thank you very much

**Comment by ludoo** [comment]
I just added a `tf_var_file` argument to `plan`, `apply` and `destroy`. Here is a simple example using it.

File `tf/main.tf`

```hcl
variable "foo" {
  type = string
}

resource "null_resource" "foo" {
  triggers = {
    foo = var.foo
  }
}

output "foo" {
  value = null_resource.foo.triggers
}
```

File `test/test_var.py`

```python
import pytest
import tftest


def test_var_file():
  tf = tftest.TerraformTest('tf')
  tf.setup(extra_files=['test.tfvars'])
  plan = tf.plan(output=True, tf_var_file='test.tfvars')
  assert 'foo' in plan.variables
  apply = tf.apply(tf_var_file='test.tfvars')
  destroy = tf.destroy(tf_var_file='test.tfvars')
  assert 'foo' in plan.variables
```

File `test.tfvars`:

```hcl
foo = "bar"
```

**Comment by ludoo** [comment]
Pushed to pypi as [1.5.1](https://pypi.org/project/tftest/1.5.1/).
