### ISSUE TITLE
Fix quoting for list variables in `tf_vars`

### ISSUE THREAD

**Issue by sklarsa** [GoogleCloudPlatform/terraform-python-testing-helper#22]
Running the latest tftest version (1.5.4)

My module has a list variable...
**variables.py**
```
variable role_policies {
  type    = list
  default = []
}
```

And when I run the following code in my test...
**test_module.py**
```
new_role = tf_plan(role_policies=["ecs_task_execution"])
```

I get the following output...
```
E       tftest.TerraformTestError: Error running command plan: 1
E       Error: Invalid character
E
E         on <value for var.role_policies> line 1:
E         (source code not available)
E
E       Single quotes are not valid. Use double quotes (") to enclose strings.
E
E
E       Error: Invalid expression
E
E         on <value for var.role_policies> line 1:
E         (source code not available)
E
E       Expected the start of an expression, but found an invalid expression token.
```

This seems similar to https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/pull/20

**Comment by ludoo** [comment]
Steven, thanks for reporting it, I'll get on it ASAP.

**Comment by ludoo** [comment]
Hah, I read that too quickly (dinner was calling), and did not spot the fact you're passing a Python list to `tf_plan`, not a Terraform list, which is a Python string. Try this

```python
new_role = tf_plan(role_policies='["ecs_task_execution"]')
```

And let me know if it works, as we're using tons of list variables in [our tests](https://github.com/terraform-google-modules/cloud-foundation-fabric/tree/master/tests) and I've never had issues with them.

**Comment by sklarsa** [comment]
Yep that works.. thanks!
