### ISSUE TITLE
[Feature-Request] AWS built-in helper functions?

### ISSUE THREAD

**Issue by marshall7m** [GoogleCloudPlatform/terraform-python-testing-helper#25]
Feature:
Add built-in AWS (or any cloud provider in general) helper functions to tftest. The built-in AWS functions can be created via boto3.

Example:

`modules/aws/ecr.py`

```
import boto3

def get_ecr_repo(name, region):
    ecr = boto3.client('ecr', region)
    response = ecr.describe_repositories(repositoryNames=[name])
    return response['repositories'][0]
```

`test_ecr_repo.py`
```
from tftest.modules.aws import ecr
import tftest

def test_apply(fixtures_dir):
  tf = tftest.TerraformTest('terraform-aws-ecr')
  tf.setup()
  tf.apply()
  
  response = ecr.get_ecr_repo('test-repo', 'us-west-2')

  tf.destroy()

```

**Comment by ludoo** [comment]
This would expand the scope of tftest too much in my opinion. But if you want to submit a PR, I'll definitely look at it. Thanks for the suggestion!

**Comment by marshall7m** [comment]
> This would expand the scope of tftest too much in my opinion. But if you want to submit a PR, I'll definitely look at it. Thanks for the suggestion!

That came across my mind too. In addition, I'm thinking users are probably going to use tftest heavily for integrations tests, especially for broad terraform modules that are stack on one another. In this case, general helper functions would only be handy for simple vanilla modules. Althought I'll think about it more this week. Thanks for giving your opinion!
