### ISSUE TITLE
How can the results generated by ‘terragrunt plan’  be converted into json

### ISSUE THREAD

**Issue by Sjenrey** [GoogleCloudPlatform/terraform-python-testing-helper#33]
Hello author, thank you for sharing your code and gaining some knowledge from your code. I would like to ask you how to convert the results generated by plan into json

**Comment by Sjenrey** [comment]
`import tftest
env = {
    "ARM_SUBSCRIPTION_ID": "x",
    "ARM_CLIENT_ID": "x",
    "ARM_CLIENT_SECRET": "x",
    "ARM_TENANT_ID": "x",
    "BLOB_ACCESS_KEY": "x"
}
fixtures_dir = 'salt-avaset/parameters/virtual_machines'
tg = tftest.TerragruntTest(fixtures_dir, env=env, tg_run_all=True)
tf_vars = {"admin_password": "x"}
result = tg.plan(output=True,tg_non_interactive=True,tf_vars=tf_vars)
print(tg.output())
`

tftest.TerraformTestError: Error decoding plan output: Expecting value: line 1 column 2 (char 1)


I have not been able to find the reason, I hope I can get your help, thank you

**Comment by Sjenrey** [comment]
> tftest.TerraformTestError: Error decoding plan output: Expecting value: line 1 column 2 (char 1)
```python
import tftest 
env = {
    "ARM_SUBSCRIPTION_ID": "x",
    "ARM_CLIENT_ID": "x",
    "ARM_CLIENT_SECRET": "x",
    "ARM_TENANT_ID": "x1",
    "BLOB_ACCESS_KEY": "x"
}
fixtures_dir = 'salt-avaset/parameters/virtual_machines' 
tg = tftest.TerragruntTest(fixtures_dir, env=env, tg_run_all=True) 
tf_vars = {"admin_password": "x"} 
result = tg.plan(output=True,tg_non_interactive=True,tf_vars=tf_vars) 
print(tg.output())
```

<font color=red>I have not been able to find the reason, I hope I can get your help, thank you!</font>

**Comment by davidtam** [comment]
hi I might get a chance to take a look but first of all https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/ - the `run-all plan` doesnt work all the time.  Does it work when you run it from cmd line not using tftest?
secondly, where is it failing?  in the `tg.plan` or `tg.output`

**Comment by Sjenrey** [comment]
> hi I might get a chance to take a look but first of all https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/ - the `run-all plan` doesnt work all the time. Does it work when you run it from cmd line not using tftest?
> secondly, where is it failing? in the `tg.plan` or `tg.output`

I am glad to hear from you.
An exception occurred during `tg.plan`
Exception prompt:“raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)” and “raise TerraformTestError('Error decoding plan output: {}'.format(e))
tftest.TerraformTestError: Error decoding plan output: Expecting value: line 1 column 2 (char 1)
”

**Comment by Sjenrey** [comment]
> hi I might get a chance to take a look but first of all https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/ - the `run-all plan` doesnt work all the time. Does it work when you run it from cmd line not using tftest?
> secondly, where is it failing? in the `tg.plan` or `tg.output`

I run the command(`terragrunt plan`) directly locally without any problems

**Comment by davidtam** [comment]
ok thanks also what are the versions of terragrunt and terraform you are using?

**Comment by Sjenrey** [comment]
> ok thanks also what are the versions of terragrunt and terraform you are using?

Finally waiting for your reply, thank you。
`Terraform v0.11.14 `，`terragrunt version v0.18.6 `

**Comment by ludoo** [comment]
@Sjenrey tftest is only compatible with Terraform >= 0.12. And thanks @davidtam for jumping on this of course!

I'll mark this as invalid, unless David wants to keep this open.

**Comment by Sjenrey** [comment]
@ludoo Thank you for your reply, my English is not good, so it will be a bit difficult to read your document, I will try to upgrade the version, thank you again for your reply, thank you

**Comment by davidtam** [comment]
@Sjenrey apologize but yeah what @ludoo said.  @ludoo yes pls close thanks!

**Comment by Sjenrey** [comment]
@davidtam What do I need to do? ^_^
