### ISSUE TITLE
How do I output the original log at the same time when I execute `tg.plan`?

### ISSUE THREAD

**Issue by Sjenrey** [GoogleCloudPlatform/terraform-python-testing-helper#35]
Excuse me, how do I output the original log at the same time when I execute `tg.plan`?
```python
tg = tftest.TerragruntTest(fixtures_dir, env=env)
tg.setup()
plan_obj = tg.plan(output=True, tf_vars=tf_vars)
format_data = plan_obj.resource_changes
```
I want to format the output while also outputting the original execution log file.
Thanks！

**Comment by davidtam** [comment]
hello are you using pytest?  If you are have you had a look [at this](https://docs.pytest.org/en/6.2.x/capture.html)?

I remember using `pytest --capture=tee-sys` worked while not interfere with the internals of tftest so pls give it a try.

**Comment by Sjenrey** [comment]
@davidtam I am sorry to reply to you so late. The method you said is ok, but it may not meet my actual needs. The scenario I use is in the web service.Thank you still for the ideas. thanks
