### ISSUE TITLE
Is it possible to test Variable Validations?

### ISSUE THREAD

**Issue by SplinterHead** [GoogleCloudPlatform/terraform-python-testing-helper#49]
I am using TFTest to help develop a module and we have some strict variable validation rules. Is it possible to test these out with TFTest?

We are looking to make sure that either the plan fails due to validation error, or that the error message is returned in the output

Currently we are just seeing "plan did not yield an output"

**Comment by ludoo** [comment]
It seems to be working fine for me. Try the following.

```hcl
# main.tf
variable "foo" {
  type = string
  validation {
    condition     = length(var.foo) > 3
    error_message = "Foo neds to be at least 3 characters."
  }
}
```

```python
# test-foo.py
import tftest


def test_plan_fail():
  tf = tftest.TerraformTest('.')
  tf.setup(upgrade=True)
  return tf.plan(output=True, tf_vars={'foo': 'bar'})


def test_plan_success():
  tf = tftest.TerraformTest('.')
  tf.setup(upgrade=True)
  return tf.plan(output=False, tf_vars={'foo': 'spam'})
```

Running `pytest`: on the good test:

```bash
pytest test-foo.py::test_plan_success
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/ludomagno/Desktop/dev/tf-tests
collected 1 item                                                                                                                                                                             

test-foo.py .                                                                                                                                                                          [100%]

===================================================================================== 1 passed in 0.06s ======================================================================================
```

Runing `pytest` on the "bad" test:

```bash
------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------
CRITICAL tftest:tftest.py:551 Error running command plan: 1  
Error: Invalid value for variable

  on main.tf line 1:
   1: variable "foo" {
    ├────────────────
    │ var.foo is "bar"

Foo neds to be at least 3 characters.

This was checked by the validation rule at main.tf:3,3-13.
================================================================================== short test summary info ===================================================================================
FAILED test-foo.py::test_plan_fail - tftest.TerraformTestError: Error running command plan: 1  
===================================================================================== 1 failed in 0.12s ======================================================================================
```

**Comment by ludoo** [comment]
Ah, I think I get your point: you would like to see the error in the exception raised, so as to be able to capture in the test?

**Comment by ludoo** [comment]
If that is the case, we probably just need to add `out` and `err` variables to the exception [raised here](https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/blob/master/tftest.py#L566).

**Comment by SplinterHead** [comment]
Correct, I would like to be able to query something like `plan.validation_messages` to see if my output is there

My current implementation is
```python
with pytest.raises(TerraformTestError) as tte:
  tf.plan(output=True, tf_vars=tf_vars)

assert "My Validation Message" in str(tte.value)
```

I'd love to be able to just check 
```python
assert "Me Validation Message" in plan.validation_messages
```

**Comment by ludoo** [comment]
> I'd love to be able to just check
> 
> ```python
> assert "Me Validation Message" in plan.validation_messages
> ```

I'm not sure it would be right to not raise an exception when a Terraform error occurs. Is there anything else that would simplify your work, without going there?

**Comment by SplinterHead** [comment]
I get your point about not raising exceptions, it does sound a bit odd now I've thought about it some more. 
Maybe just your suggestion then of adding `out` and `err` to the Exception?

**Comment by ludoo** [comment]
> I get your point about not raising exceptions, it does sound a bit odd now I've thought about it some more. Maybe just your suggestion then of adding `out` and `err` to the Exception?

Ok great, that is very doable. I can prepare a PR hopefully later today, or feel free of course to send one before if you like.
