### ISSUE TITLE
Handling prevent destroy within tests scenarios for module have other module dependencies 

### ISSUE THREAD

**Issue by crjlty88** [GoogleCloudPlatform/terraform-python-testing-helper#59]
Similar situation with #42, if a module inside have other module dependencies have prevent destroy will cause the test will fail because current `disable_prevent_destroy` option only update terraform file in current folder, and this operation should apply to all terraform within `.terraform/modules` folder.

**Comment by ludoo** [comment]
I don't see this as simple or straightforward to implement. The best workaround for this kind of situations is to implement it in a custom test fixture. Closing this, but feel free to reopen if you figure out a simple way of doing it.
