### ISSUE TITLE
Allow access to values from data lookups in plan tests

### ISSUE THREAD

**Issue by fergoid** [GoogleCloudPlatform/terraform-python-testing-helper#75]
Data lookup 'resources' are available in the Terraform plan under 'prior_state'.  Could this be exposed by the tftest plan method?

**Comment by ludoo** [comment]
Would you care sending a PR?

**Comment by fergoid** [comment]
Sure I will do that.

Mark.

**Comment by fergoid** [comment]
I noticed all the Python indents in the files are 2 spaces but I am getting this warning
PEP 8: E111 indentation is not a multiple of 4

Am I okay to reformat the files ?

**Comment by ludoo** [comment]
Nope :) just set your linter to 2 spaces

**Comment by ludoo** [comment]
This has now been released in v1.8.5

https://pypi.org/project/tftest/1.8.5/
