### ISSUE TITLE
KeyError: 'outputs' when loading a big json plan output

### ISSUE THREAD

**Issue by guimaluf** [GoogleCloudPlatform/terraform-python-testing-helper#9]
I'm trying to test my module, but when I run `pytest` with my json I'm getting this error

```
fixtures_dir = '/home/guimaluf/workspace/rcs-as-code/test/fixtures'

    @pytest.fixture
    def plan_out(fixtures_dir):
        import json
        with open('%s/rcs_as_code.show.json' % fixtures_dir) as fp:
>           return tftest.TerraformPlanOutput(json.load(fp))

test_rcs_as_code.py:10:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tftest.TerraformPlanOutput object at 0x7f01785b12e0>
raw = {'configuration': {'provider_config': {'gitlab': {'expressions': {'base_url': {'constant_value': 'https://gitlab.devel...rces': [{'address': 'data.external.mcs94', 'mode': 'data', 'name': 'asd21', 'provider_name': 'external', ...}]}}}, ...}

    def __init__(self, raw):
      super(TerraformPlanOutput, self).__init__(raw)
      self.root_module = TerraformPlanModule(
          raw['planned_values']['root_module'])
>     self.outputs = TerraformValueDict(raw['planned_values']['outputs'])
E     KeyError: 'outputs'

lib/python3.8/site-packages/tftest.py:169: KeyError
```

I'm generating json with
```
terraform plan -out tfm.plan
terraform show -json tfm.plan > rcs_as_code.show.json
```

Using 
```Test session starts (platform: linux, Python 3.8.0, pytest 5.3.1, pytest-sugar 0.9.2)```

Please let me know If I need to provide additional info

**Comment by ludoo** [comment]
How does the `rcs_as_code.show.json` file look like? Has it got a `planned_values` key in it, and what does it contain? Probably not relevant, but what Terraform version are you using?

**Comment by guimaluf** [comment]
Terraform v0.12.17
Yes, the json file has `planned_values`. I sanitize my json, here it is 

https://pastebin.com/qpVXjwuz

This is my pytest code. 
```
import pytest
import tftest

@pytest.fixture
def plan_out(fixtures_dir):
    import json
    with open('%s/rcs_as_code.show.json' % fixtures_dir) as fp:
        return tftest.TerraformPlanOutput(json.load(fp))

def test_output(plan_out):
    assert plan_out.terraform_version == '0.12.17'
```

**Comment by ludoo** [comment]
Thanks for the pastebin. Have you got any outputs defined in the root module? Did you ever run `apply` before running `plan out`? I think both conditions need to be true for outputs to be present in your plan out. Can you try running `apply` and re-running `plan out`?

**Comment by guimaluf** [comment]
I'm quite new to terraform. That manner I'm trying a more providers/resources agnostic type of tests. Unfortunately it doesn't seems to be that possible, right?

ATM I don't have the credentials to run apply in the code I'm testing. After doing this I'll try to get the plan out and rerun the tests.

Thanks :)

**Comment by ludoo** [comment]
You can probably test other data present in the plan out without having to run apply. Have a look at the json file for plan out, it might contain what you need.

For example,  `planned_values.root_module.child_modules` is a list of all child modules and their resources, so you can test which ones are present where, and their attributes.

Then if the library is making it hard to get at that information, we can see how to support it better.

**Comment by guimaluf** [comment]
Thank you for your support. I'm struggling to make tftest works.
Would be good to have a more detailed instructions on how to generate the right input for tftest.

Even with simpler module I'm finding quite hard to test them out
